### ISSUE TITLE
Error when doing ':wq' with newer vim version

### ISSUE THREAD

**Issue by gobenji** [jamessan/vim-gnupg#111]
After upgrading from vim 8.1.2269 to 8.2.439 (on Debian unstable) the behavior changed when editing a gpg file and doing ':wq'. vim now reports "E13: File exists (add ! to override)". Forcing it with ":wq!" works as expected. Is it possible to have to old behavior back? That would keep the user experience consistent between editing normal files and gpg files.

**Comment by jamessan** [comment]
This is a [bug](https://github.com/vim/vim/issues/5807) in Vim, which was fixed in [v8.2.0474](https://github.com/vim/vim/commit/0fff44152d06e6b662ad4bef172af07a041d2f3f).  It was introduced by [v8.2.0403](https://github.com/vim/vim/commit/a3a9c8ef697bbf6f640cde99710b6f534f29f77d#diff-25d902c24283ab8cfbac54dfa101ad31).

I'll upload a new Vim version to Debian soon.

**Comment by gobenji** [comment]
Oh, I see. Thanks a lot for the clarification.
