### ISSUE TITLE
yank to system clipboard ("+y) not working

### ISSUE THREAD

**Issue by mortenbh** [jamessan/vim-gnupg#36]
Hi,

I noticed another issue, namely that yanking to the system clipboard is not working. I am not sure if this is intentional or not? Since I store my passwords in a GPG encrypted file, I would like to yank the password to the system clipboard.

Note, when editing any unencrypted file, yanking to the clipboard (e.g "+yy to yank the current line) works without issue. I also tried :set viminfo=, :set noswapfile, :set noundofile when editing any unencrypted file to see if any of these options were causing the clipboard to stop working, but this does not seem to be the issue.

I am using KDE @ Debian/jessie and Vim in Konsole.

**Comment by jamessan** [comment]
There are a few issues involved here.

1. After letting gpg-agent handle the passphrase entry, Vim's terminal state isn't correct so things like arrow keys no longer work (#17).
 * It's not clear to me yet whether this is an issue with Vim not setting the terminal back to a certain state before invoking pinentry or with pinentry's handling of the terminal settings.
1. In order to work around that issue, I changed (bd3ebdff6cb18d09c4bdbb72e28e07841c5076eb) vim-gnupg to re-set the terminal type after decrypting the file.  This causes Vim to fix up its terminal state, but it happens to also cause Vim to forget that it can talk to X's clipboard.
 * I [reported](http://news.gmane.org/find-root.php?message_id=20141202055144.GD13546%40freya.jamessan.com) a bug upstream, but Bram wasn't receptive to the fix.  I haven't had time to revisit that yet, either to push on that fix again or try to come up with a more palatable fix.

I'll add documentation about this to the `Known Issues` part of the documentation so people don't keep unknowingly tripping over it.  Hopefully I'll also have some time to try and get the core issues fixed in vim/pinentry.

**Comment by powerman** [comment]
Is there any workaround for this issue?

**Comment by jamessan** [comment]
You can use an external tool like xclip -- `:call system('xclip -i -selection clipboard', getreg('"'))`

**Comment by thelollies** [comment]
I've got the same issue. It's a shame your bug report wasn't acted upon.

**Comment by powerman** [comment]
@thelollies It's an open source. Only good reason to feel shame is when **you** blame someone else instead of fixing issue yourself and making pull request with a fix.

**Comment by thelollies** [comment]
The bug has already been filed and a fix suggested but it was dismissed.

**Comment by powerman** [comment]
There are number of tools like xclip, xsel, pbcopy… they ain't installed everywhere, they often have different issues with copying Unicode or fail to keep selection or daemonize themselves to keep selection etc. - i.e. there are side effects and related issues. I've played with them several years ago and drop them all from .vimrc as soon as Vim became able to correctly work with XClipboard on it's own. And, personally, I don't like to return to using these tools once again in .vimrc.

I mean, such workaround isn't a good enough candidate to be included in plugin's code. Probably if someone will develop separate vim plugin which implements support for copy&paste in universal enough way, automatically choosing tools available on that system and including all required workarounds to make these tools works correctly and without side effects - then using such plugin in this one might make sense.

**Comment by thelollies** [comment]
>There are number of tools like xclip, xsel, pbcopy… they ain't installed everywhere

Yep, I don't have `xclip` and I do have `pbcopy` which is why I'm sharing my `pbcopy` workaround.

>they often have different issues with copying Unicode or fail to keep selection or daemonize themselves to keep selection etc. - i.e. there are side effects and related issues

Definitely, I wouldn't suggest anyone use the code I provided as their usual copy/paste functionality. It's good enough for this basic use case though.

>such workaround isn't a good enough candidate to be included in plugin's code

I agree, that's why it's a code snippet in a Github issue rather than a pull request.

**Comment by jdelisle** [comment]
@thelollies thanks for that workaround, that's pretty useful for me in the meantime anyway.

@jamessan thanks for your support on this issue! perhaps you forgot to add it to the `Known Issues`? :)

**Comment by jamessan** [comment]
As of [7.4.959](https://github.com/vim/vim/releases/tag/v7.4.959), interaction with the clipboard should work again.

**Comment by jdelisle** [comment]
@jamessan nice, that is good news! I've just tested it and it works indeed, thanks! :)
