### ISSUE TITLE
t_Co is unset somehow by vim-gnupg

### ISSUE THREAD

**Issue by darthcloud** [jamessan/vim-gnupg#57]
I use a fancy colorscheme that need 256 colors and so II use "set t_Co=256" in my vimrc.

Somehow to get unset when I load a gpg file. I have to set it back manually to get the color from my scheme.

Any idea why?

**Comment by jamessan** [comment]
Yes.  You're setting `t_Co` in your vimrc.

Due to a bug in the interaction between Vim and gpg/pinentry (described in #17), I had to change the plugin to rediscover the terminal settings after running gpg.  This is undoing your manual setting of `t_Co`.

You can either configure your terminal to advertise the correct `$TERM` (e.g., `xterm-256color` if you're using xterm), which would allow Vim to automatically set `t_Co` appropriately, or set `t_Co` in a `TermChanged` autocmd:

    au TermChanged * set t_Co=256

Fixing your terminal is the better solution.

**Comment by darthcloud** [comment]
On Thu, Jan 7, 2016 at 6:24 PM, James McCoy <notifications@github.com>
wrote:

> , xterm-256color
>

Thanks for the info, work fine now. :)

Jacques Gagnon
GTalk/E-Mail: darthcloud@gmail.com
WLM (MSN): cloud3334@msn.com
