### ISSUE TITLE
A file that I've been opening and writing to no longer decrypts

### ISSUE THREAD

**Issue by DemarcatedTitle** [jamessan/vim-gnupg#71]
I hope I'm posting this in the appropriate place. 

But yeah, I've been writing to this file not every day but pretty frequently using this plugin and today it's not decrypting. I've been looking around for information on gpg and through the stuff here, but I'm my knowledge on encryption is pretty miniscule so not all of it is making sense to me. 

I was wondering if I have any recourse for this, though? I've checked with an older version of the file from a month ago and I know I'm entering the right passphrase, unless that was changed some how through some kind of corruption. 

So if I can open the older one but not the newest copy of the file, does that mean it was corrupted and is lost for good? If that is the case, what would be the best way to guard myself against it in the future? 

And a thing I just noticed, apparently the version I installed with vim-addon-manager is from may 31, 2012, if that means anything for this.

**Comment by jamessan** [comment]
Since you haven't specified, it sounds like you're using symmetric encryption to encrypt a file with a password rather than using a gpg key to encrypt a file.

> I've checked with an older version of the file from a month ago and I know I'm entering the right passphrase, unless that was changed some how through some kind of corruption.

Or through mistyping it the last time you saved it.  Assuming you are using symmetric encryption, every time you save, you have to re-enter the password, so just because you're able to correctly type the password to decrypt an older file doesn't mean you typed it correctly when you saved the problematic file.

> If that is the case, what would be the best way to guard myself against it in the future?

Either ensuring you're able to decrypt it before closing Vim or switching to using gpg's asymmetric encryption, so you just need to enter your gpg key's password to decrypt it.

**Comment by DemarcatedTitle** [comment]
Thanks for getting back to me so quickly. I've been meaning to respond. 

Yeah, that's all accurate. I assumed that it made you type in the same password to save, so I guess I got sloppy.
